server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway_info
          uri: http://localhost:${server.port}
          predicates:
            - Path=/actuator/info
        - id: provider_router
          uri: lb://cloud-provider-service
          predicates:
            - Path=/provider/**
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


info:
  app.name: cloud-gateway-9527
  app.port: 9527
  app.author.name: crudcoder
  app.author.email: 710683598@qq.com
  app.create.date: 2020-4-6