server:
  port: 80

ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
logging:
  level:
    com.coder.cloud.service: debug

#如果不改为true 则feign的fallback功能无法开启
feign:
  hystrix:
    enabled: true

info:
  app.name: cloud-consumer-service
  app.port: 80
  app.author.name: crudcoder
  app.author.email: 710683598@qq.com
  app.author.github: https://github.com/CRUDCODER
  app.create.date: 2020-4-6
spring:
  application:
    name: cloud-consumer-service